components:
  schemas:
    Produkt:
      title: Produkt
      type: object
      properties:
        produktCode:
          $ref: >-
            ../fields/com/Produkt/produktCode.yaml#/components/schemas/produktCode
        codeProdukteigenschaft:
          $ref: >-
            ../fields/com/Produkt/codeProdukteigenschaft.yaml#/components/schemas/codeProdukteigenschaft
        wertedetails:
          $ref: >-
            ../fields/com/Produkt/wertedetails.yaml#/components/schemas/wertedetails
